version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: g2_safespace
      MYSQL_USER: pepega
      MYSQL_PASSWORD: clap
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot:
    image: mirohin/safespace_server:server1.7 # This should be the name of your Spring Boot app image
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/g2_safespace
      SPRING_DATASOURCE_USERNAME: pepega
      SPRING_DATASOURCE_PASSWORD: clap
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
