version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: g2_safespace
      MYSQL_USER: pepega
      MYSQL_PASSWORD: clap
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      MYSQL_DATABASE: g2_safespace
      MYSQL_USER: pepega
      MYSQL_PASSWORD: clap
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "8080:8080"
    depends_on:
      - db