package G2.SafeSpace.entity;

import jakarta.persistence.*;

/**
 * The Message entity represents a message in the system.
 * It includes the message's content, a unique identifier for the message,
 * and the date the message was created. This entity is mapped to the "messages" table in the database.
 */
@Entity
@Table(name = "messages")
public class Message {

    /**
     * The unique identifier for this message.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int messageID;

    /**
     * The content of the message.
     * This field holds the actual text of the message.
     */
    @Column
    private String messageContent;

    /**
     * The date the message was created.
     * This field is read-only and is not updatable or insertable through JPA.
     * It is typically set by the database.
     */
    @Column(insertable = false, updatable = false)
    private String dateOfMessage;

    /**
     * Default constructor for the Message class.
     * This constructor is used to create an empty Message object.
     */
    public Message() {}

    /**
     * Retrieves the unique identifier of the message.
     *
     * @return the message's ID
     */
    public int getMessageID() {
        return this.messageID;
    }

    /**
     * Retrieves the content of the message.
     *
     * @return the content of the message
     */
    public String getMessageContent() {
        return this.messageContent;
    }

    /**
     * Retrieves the date the message was created.
     *
     * @return the date of the message creation
     */
    public String getDateOfMessage() {
        return this.dateOfMessage;
    }

    /**
     * Sets the content of the message.
     *
     * @param messageContent the content to set for the message
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * Returns a string representation of the message, including the message's ID,
     * content, and creation date.
     *
     * @return a string containing the message details
     */
    @Override
    public String toString() {
        return "Message = ID: " + this.messageID + ", CONTENT: " + this.messageContent + ", DATE: " + this.dateOfMessage;
    }
}
